### PR TITLE
update to the current live patch

### PR DESCRIPTION
**Pull request by Arctice**
Updated the interface value, and made PLAYER_ENTERING_WORLD not haphazardly delete all your old favourites.

### CODE REVIEW

**Comment by Arctice** [comment]
if I understand correctly you're no longer subscribed to the game - if so, and if it's okay with you, I could take over mantaining the addon here and over on Curse.

**Comment by meribold** [comment]
Looks good on first glance.  I'll take a closer look this weekend.  Can you
revert the changes that have no effect at the top of the file and stick to
the existing naming convention instead of using Python style?  Sorry for
wiping your favorites.

**Comment by meribold** [comment]
Yeah, I think I can make you the maintainer on Curse.  I'm probably not
resubscribing in the near future.

**Comment by Arctice** [comment]
Alright - renamed the variables. The reason I stuck the first load flag in the FavouriteMounts table is I didn't want to mess too much with the rest of the code for now.

**Comment by meribold** [comment]
I think most addons only have one table as their only saved variable to minimize pollution of the shared namespace, so sticking this information into `FavoriteMounts` makes sense (the name is just kind of bad now).  I was thinking you could just check if the `FavoriteMounts` table is empty, but that would cause issues when a character is supposed to have no favorites I guess.

Can you send me a PM on Curse so I know who you are?

**Comment by Arctice** [comment]
Messaged! Yeah that was my guess as well apropos saved variables; might have to rename "FavouriteMounts" to something including the addon name in the future

**Pull request merged**
